import { Link } from 'react-router-dom'
import illustration from '../assets/auth-illustration.svg'
import AmbientParticles from '../components/AmbientParticles'
const Doodle=()=> <svg className="doodle" viewBox="0 0 100 48" aria-hidden="true"><path d="M4 10c18-9 29 17 46 10 12-5 3-15-6-8M82 11c7 6 9 16 3 28M76 31l9 9 10-7"/></svg>
function Home(){return <div className="page-container"><section className="hero hero--with-illustration"><AmbientParticles id="home-particles"/><div className="hero-content"><span className="eyebrow">Study, made clearer</span><h1>Make every study hour <em className="accent-word">count.</em></h1><p className="hero-copy">A calmer way to organize your work, build better habits, and see real progress - without the scramble.</p><div className="hero-actions"><Link className="button button--accent" to="/dashboard">Build my study plan ?</Link><Link className="button button--soft" to="/services">Explore tools</Link><Doodle/></div></div><div className="hero-illustration"><img src={illustration} alt="Colorful study notes and planning cards" /></div></section><section className="section"><div className="section-heading"><div><span className="eyebrow">Everything in one place</span><h2>A focused toolkit for <em className="coral-word">better</em> learning.</h2></div><p>Less time piecing together a system. More time actually understanding the material.</p></div><div className="card-grid"><article className="card"><div className="card-badge">?</div><h3>Smart study plans</h3><p>Turn big goals into a gentle, realistic sequence of daily sessions.</p><Link className="card-link" to="/services">See how it works ?</Link></article><article className="card"><div className="card-badge">?</div><h3>Clarity, on demand</h3><p>Capture questions, notes, and ideas while they are still fresh.</p><Link className="card-link" to="/services">Explore notes ?</Link></article><article className="card"><div className="card-badge">?</div><h3>Visible momentum</h3><p>Small wins add up. Follow your progress without turning it into pressure.</p><Link className="card-link" to="/dashboard">View dashboard ?</Link></article></div></section><section className="feature-panel"><div><span className="eyebrow">Your learning rhythm</span><h2>Study with direction, not just <em>determination.</em></h2><p>Studybuddy holds the plan, so you can hold onto your attention.</p></div><div className="feature-points"><div className="feature-point"><span>?</span>One clear next step, every day</div><div className="feature-point"><span>?</span>Flexible enough for real life</div><div className="feature-point"><span>?</span>Progress you can actually feel</div></div></section></div>};export default Home





